- name: Instalar git, docker-compose y jq en n m치quinas
  hosts: servers
  become: yes
  tasks:
    - name: Asegurarse de que el paquete epel-release est치 instalado
      yum:
        name: epel-release
        state: present

    - name: Instalar git
      yum:
        name: git
        state: present

    - name: Verificar si Docker ya est치 instalado
      command: which docker
      register: docker_installed
      ignore_errors: true

    - name: Instalar Docker si no est치 instalado
      yum:
        name: docker
        state: present
      when: docker_installed.rc != 0

    - name: Iniciar y habilitar el servicio de Docker
      service:
        name: docker
        state: started
        enabled: yes
      when: docker_installed.rc != 0

    - name: Instalar docker-compose
      yum:
        name: docker-compose
        state: present

    - name: Instalar jq
      yum:
        name: jq
        state: present
